"""init_mysql

Revision ID: 261e4f25bece
Revises: 
Create Date: 2026-02-03 18:53:28.860320
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '261e4f25bece'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ac_switch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('switch', sa.Boolean(), nullable=False),
    sa.Column('app_id', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=50), nullable=True),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.Column('delete_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ac_switch_app_id'), 'ac_switch', ['app_id'], unique=False)
    op.create_index(op.f('ix_ac_switch_channel'), 'ac_switch', ['channel'], unique=False)
    op.create_table('ai_switch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('switch', sa.Boolean(), nullable=False),
    sa.Column('app_id', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=50), nullable=True),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.Column('delete_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_switch_app_id'), 'ai_switch', ['app_id'], unique=False)
    op.create_table('app',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('access_key', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=50), nullable=True),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.Column('delete_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_app_id'), 'app', ['app_id'], unique=False)
    op.create_table('channel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('no', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=50), nullable=True),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.Column('delete_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_no'), 'channel', ['no'], unique=False)
    op.create_table('language',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbrev', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=50), nullable=True),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.Column('delete_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_abbrev'), 'language', ['abbrev'], unique=False)
    op.create_table('list_app_channel',
    sa.Column('list_no', sa.String(length=100), nullable=False),
    sa.Column('app_id', sa.String(length=100), nullable=False),
    sa.Column('channel_no', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=50), nullable=True),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.Column('delete_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('list_no', 'app_id', 'channel_no')
    )
    op.create_table('list_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('list_no', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=50), nullable=True),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.Column('delete_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_detail_list_no'), 'list_detail', ['list_no'], unique=False)
    op.create_table('model_threshold',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.String(length=100), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=50), nullable=True),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.Column('delete_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_threshold_app_id'), 'model_threshold', ['app_id'], unique=False)
    op.create_table('name_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('no', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('match_rule', sa.Integer(), nullable=True),
    sa.Column('match_type', sa.Integer(), nullable=True),
    sa.Column('suggest', sa.Integer(), nullable=True),
    sa.Column('risk_type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=50), nullable=True),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.Column('delete_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_name_list_no'), 'name_list', ['no'], unique=True)
    op.create_table('risk_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=False),
    sa.Column('abbrev', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=50), nullable=True),
    sa.Column('update_by', sa.String(length=50), nullable=True),
    sa.Column('delete_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_type_no'), 'risk_type', ['no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_type_no'), table_name='risk_type')
    op.drop_table('risk_type')
    op.drop_index(op.f('ix_name_list_no'), table_name='name_list')
    op.drop_table('name_list')
    op.drop_index(op.f('ix_model_threshold_app_id'), table_name='model_threshold')
    op.drop_table('model_threshold')
    op.drop_index(op.f('ix_list_detail_list_no'), table_name='list_detail')
    op.drop_table('list_detail')
    op.drop_table('list_app_channel')
    op.drop_index(op.f('ix_language_abbrev'), table_name='language')
    op.drop_table('language')
    op.drop_index(op.f('ix_channel_no'), table_name='channel')
    op.drop_table('channel')
    op.drop_index(op.f('ix_app_app_id'), table_name='app')
    op.drop_table('app')
    op.drop_index(op.f('ix_ai_switch_app_id'), table_name='ai_switch')
    op.drop_table('ai_switch')
    op.drop_index(op.f('ix_ac_switch_channel'), table_name='ac_switch')
    op.drop_index(op.f('ix_ac_switch_app_id'), table_name='ac_switch')
    op.drop_table('ac_switch')
    # ### end Alembic commands ###
