"""channel_id

Revision ID: 5af2e718ca64
Revises: 261e4f25bece
Create Date: 2026-02-03 19:00:26.415531
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import mysql

revision = '5af2e718ca64'
down_revision = '261e4f25bece'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_app_channel', sa.Column('channel_id', sa.Integer(), nullable=True))
    conn = op.get_bind()
    conn.execute(
        text(
            """
            UPDATE list_app_channel lac
            JOIN channel c ON lac.channel_no = c.no
            SET lac.channel_id = c.id
            """
        )
    )
    op.alter_column('list_app_channel', 'channel_id', nullable=False)
    op.drop_index(op.f('ix_channel_no'), table_name='channel')
    op.drop_column('channel', 'no')
    op.drop_column('list_app_channel', 'channel_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'channel',
        sa.Column('no', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True),
    )
    conn = op.get_bind()
    conn.execute(text("UPDATE channel SET no = CAST(id AS CHAR(100))"))
    op.alter_column('channel', 'no', nullable=False)
    op.create_index(op.f('ix_channel_no'), 'channel', ['no'], unique=False)
    op.add_column(
        'list_app_channel',
        sa.Column('channel_no', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True),
    )
    conn.execute(
        text(
            """
            UPDATE list_app_channel lac
            JOIN channel c ON lac.channel_id = c.id
            SET lac.channel_no = c.no
            """
        )
    )
    op.alter_column('list_app_channel', 'channel_no', nullable=False)
    op.drop_column('list_app_channel', 'channel_id')
    # ### end Alembic commands ###
